// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260628115651_SeedColorsAndSizes")]
    partial class SeedColorsAndSizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("API.Entity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Entity.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Description = "Lorem ipsum dolor sit amet consectetur adipiscing elit dolor",
                            ImageUrl = "campaigns/banner1.png",
                            Index = 0,
                            Title = "Fashion Month Ready in Capital Shop"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet consectetur adipiscing elit dolor",
                            ImageUrl = "campaigns/banner2.png",
                            Index = 1,
                            Title = "Fashion Month Ready in Capital Shop"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Description = "Lorem ipsum dolor sit amet consectetur adipiscing elit dolor",
                            ImageUrl = "campaigns/banner3.png",
                            Index = 2,
                            Title = "Fashion Month Ready in Capital Shop"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Lorem ipsum dolor sit amet consectetur adipiscing elit dolor",
                            ImageUrl = "campaigns/banner4.png",
                            Index = 3,
                            Title = "Fashion Month Ready in Capital Shop"
                        });
                });

            modelBuilder.Entity("API.Entity.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("API.Entity.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beden")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Renk")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("UrunId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("API.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "categories/categories1.png",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "categories/categories2.png",
                            Name = "Watches"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "categories/categories3.png",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "categories/categories4.png",
                            Name = "Furnitures"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "categories/categories5.png",
                            Name = "Collections"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "categories/categories6.png",
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("API.Entity.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HOSGELDIN10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 10
                        },
                        new
                        {
                            Id = 2,
                            Code = "YAZA20",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 20
                        });
                });

            modelBuilder.Entity("API.Entity.CouponUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.ToTable("CouponUsages");
                });

            modelBuilder.Entity("API.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresSatiri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AraToplam")
                        .HasColumnType("REAL");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IyzicoPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IyzicoToken")
                        .HasColumnType("TEXT");

                    b.Property<double>("KuponIndirimi")
                        .HasColumnType("REAL");

                    b.Property<string>("KuponKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiparisNotu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TeslimatUcreti")
                        .HasColumnType("REAL");

                    b.Property<double>("Toplam")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beden")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunResmi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UrunId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Discount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NewPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("OldPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Klasik tasarımı ve dayanıklı reçine kayışıyla günlük kullanım için ideal bir saat kayışı. Su geçirmez yapısı ve ayarlanabilir tokalı sistemiyle her bilek ölçüsüne uyum sağlar. Minimalist estetiği modern gardıroplarla mükemmel uyum içindedir.",
                            Discount = 22,
                            Name = "Analogue Resin Strap",
                            NewPrice = 108.0,
                            OldPrice = 165.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Yüksek bel kesimi ve vücudu saran fit yapısıyla Ridley High Waist, şıklığı konforu ile buluşturuyor. %95 pamuk, %5 elastan karışımıyla nefes alabilir bir his sunar. Her vücut tipine uygun tasarımı sayesinde hem günlük hem de özel davetler için tercih edilebilir.",
                            Discount = 33,
                            Name = "Ridley High Waist",
                            NewPrice = 100.0,
                            OldPrice = 208.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Soğuk kış günlerinde başınızı sıcak tutacak Blush Beanie, yumuşak dokulu akrilik iplikten üretilmiştir. Pembe tonlarıyla tatlı ve şık bir görünüm sunar. Unisex tasarımı sayesinde her yaşa ve stile hitap eder.",
                            Discount = 90,
                            Name = "Blush Beanie",
                            NewPrice = 38.0,
                            OldPrice = 165.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Mercury Tee, %100 organik pamuktan üretilmiş çevre dostu bir günlük t-shirt seçeneğidir. Hafif ve nefes alabilir kumaşı ile yaz aylarının vazgeçilmezi olacak. Sade kesimi ve farklı renk seçenekleriyle her kombine kolayca uyum sağlar.",
                            Discount = 40,
                            Name = "Mercury Tee",
                            NewPrice = 48.0,
                            OldPrice = 165.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Bohem ruhunu rose gold detaylarla birleştiren La Bohème, özel anlarınız için tasarlanmış zarif bir aksesuar koleksiyonudur. El yapımı işçiliği ve titiz detaylarıyla göz alıcı bir şıklık sunar. Sevdiklerinize özel bir hediye seçeneği olarak da tercih edilebilir.",
                            Discount = 40,
                            Name = "La Bohème Rose Gold",
                            NewPrice = 48.0,
                            OldPrice = 165.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Yüksek bel kesimi ve vücudu saran fit yapısıyla Ridley High Waist, şıklığı konforu ile buluşturuyor. Özel dikiş teknolojisi sayesinde uzun süreli kullanımda bile şeklini korur.",
                            Discount = 33,
                            Name = "Ridley High Waist",
                            NewPrice = 100.0,
                            OldPrice = 208.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "El örgüsü dokusunu andıran Blush Beanie, kışın en sevilen aksesuar parçalarından biri olmaya aday. Yumuşak iç astarı ile uzun süre konforlu kullanım sağlar. Katlanabilir ağız kısmı istediğiniz uzunlukta kullanmanıza olanak tanır.",
                            Discount = 90,
                            Name = "Blush Beanie",
                            NewPrice = 38.0,
                            OldPrice = 165.0
                        });
                });

            modelBuilder.Entity("API.Entity.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#000000",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#b40606",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#000000",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            Color = "#8c0808",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            Color = "#bebebe",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            Color = "#161212",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            Color = "#000000",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 8,
                            Color = "#d1cbcb",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 9,
                            Color = "#3c4d84",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 10,
                            Color = "#707174",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 11,
                            Color = "#040506",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 12,
                            Color = "#000000",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 13,
                            Color = "#a15555",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 14,
                            Color = "#000000",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            Color = "#d92a2a",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 16,
                            Color = "#878181",
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("API.Entity.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            ProductId = 1,
                            Url = "products/product1/1.png"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = false,
                            ProductId = 1,
                            Url = "products/product1/2.png"
                        },
                        new
                        {
                            Id = 3,
                            IsMain = false,
                            ProductId = 1,
                            Url = "products/product1/3.png"
                        },
                        new
                        {
                            Id = 4,
                            IsMain = true,
                            ProductId = 2,
                            Url = "products/product2/1.png"
                        },
                        new
                        {
                            Id = 5,
                            IsMain = false,
                            ProductId = 2,
                            Url = "products/product2/2.png"
                        },
                        new
                        {
                            Id = 6,
                            IsMain = false,
                            ProductId = 2,
                            Url = "products/product2/3.png"
                        },
                        new
                        {
                            Id = 7,
                            IsMain = true,
                            ProductId = 3,
                            Url = "products/product3/1.png"
                        },
                        new
                        {
                            Id = 8,
                            IsMain = false,
                            ProductId = 3,
                            Url = "products/product3/2.png"
                        },
                        new
                        {
                            Id = 9,
                            IsMain = false,
                            ProductId = 3,
                            Url = "products/product3/3.png"
                        },
                        new
                        {
                            Id = 10,
                            IsMain = true,
                            ProductId = 4,
                            Url = "products/product4/1.png"
                        },
                        new
                        {
                            Id = 11,
                            IsMain = false,
                            ProductId = 4,
                            Url = "products/product4/2.png"
                        },
                        new
                        {
                            Id = 12,
                            IsMain = false,
                            ProductId = 4,
                            Url = "products/product4/3.png"
                        },
                        new
                        {
                            Id = 13,
                            IsMain = true,
                            ProductId = 5,
                            Url = "products/product5/1.png"
                        },
                        new
                        {
                            Id = 14,
                            IsMain = false,
                            ProductId = 5,
                            Url = "products/product5/2.png"
                        },
                        new
                        {
                            Id = 15,
                            IsMain = false,
                            ProductId = 5,
                            Url = "products/product5/3.png"
                        },
                        new
                        {
                            Id = 16,
                            IsMain = true,
                            ProductId = 6,
                            Url = "products/product1/1.png"
                        },
                        new
                        {
                            Id = 17,
                            IsMain = false,
                            ProductId = 6,
                            Url = "products/product1/2.png"
                        },
                        new
                        {
                            Id = 18,
                            IsMain = false,
                            ProductId = 6,
                            Url = "products/product1/3.png"
                        },
                        new
                        {
                            Id = 19,
                            IsMain = true,
                            ProductId = 7,
                            Url = "products/product2/1.png"
                        },
                        new
                        {
                            Id = 20,
                            IsMain = false,
                            ProductId = 7,
                            Url = "products/product2/2.png"
                        },
                        new
                        {
                            Id = 21,
                            IsMain = false,
                            ProductId = 7,
                            Url = "products/product2/3.png"
                        });
                });

            modelBuilder.Entity("API.Entity.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("API.Entity.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Size = 0,
                            Stock = 2
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Size = 1,
                            Stock = 5
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Size = 3,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            Size = 2,
                            Stock = 3
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 2,
                            Size = 0,
                            Stock = 1
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            Size = 2,
                            Stock = 2
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            Size = 4,
                            Stock = 4
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 2,
                            Size = 3,
                            Stock = 2
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 3,
                            Size = 1,
                            Stock = 5
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 3,
                            Size = 2,
                            Stock = 4
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 3,
                            Size = 3,
                            Stock = 0
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 4,
                            Size = 1,
                            Stock = 2
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 4,
                            Size = 2,
                            Stock = 0
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 4,
                            Size = 3,
                            Stock = 3
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 5,
                            Size = 3,
                            Stock = 2
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 5,
                            Size = 5,
                            Stock = 3
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 5,
                            Size = 6,
                            Stock = 4
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 6,
                            Size = 1,
                            Stock = 4
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 6,
                            Size = 0,
                            Stock = 5
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 6,
                            Size = 2,
                            Stock = 2
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 6,
                            Size = 3,
                            Stock = 3
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 7,
                            Size = 2,
                            Stock = 5
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 7,
                            Size = 3,
                            Stock = 3
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 7,
                            Size = 5,
                            Stock = 2
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 7,
                            Size = 4,
                            Stock = 4
                        });
                });

            modelBuilder.Entity("API.Entity.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            Index = 0,
                            Resim = "slider/slider1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            Index = 1,
                            Resim = "slider/slider2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            Index = 2,
                            Resim = "slider/slider3.jpg"
                        });
                });

            modelBuilder.Entity("Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fashion dünyasında öne çıkan ürünleri keşfedin.",
                            Img = "blogs/blog1.jpg",
                            Title = "The Best Products That Shape Fashion",
                            UpdatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sokak modasında yeni trendler ve kombin önerileri.",
                            Img = "blogs/blog2.jpg",
                            Title = "Modern Street Style Trends",
                            UpdatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lüks markaların stil dünyasına etkisi.",
                            Img = "blogs/blog3.jpg",
                            Title = "Luxury Brands That Define Elegance",
                            UpdatedDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Entity.CartItem", b =>
                {
                    b.HasOne("API.Entity.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entity.Product", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("API.Entity.CouponUsage", b =>
                {
                    b.HasOne("API.Entity.Coupon", "Coupon")
                        .WithMany("Usages")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("API.Entity.OrderItem", b =>
                {
                    b.HasOne("API.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entity.Product", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.HasOne("API.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API.Entity.ProductColor", b =>
                {
                    b.HasOne("API.Entity.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Entity.ProductImage", b =>
                {
                    b.HasOne("API.Entity.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Entity.ProductReview", b =>
                {
                    b.HasOne("API.Entity.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entity.ProductSize", b =>
                {
                    b.HasOne("API.Entity.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("API.Entity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("API.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("API.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("API.Entity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("API.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entity.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("API.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("API.Entity.Coupon", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("API.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Images");

                    b.Navigation("ProductReviews");

                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
